---
# Author: DALQUINT - denny.alquinta@oracle.com 
# Purpose: Run all generic pre execution tasks
#         
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
#

- name : "PREEXEC - [1/1] - Copy the keys to the corresponding paths for pack exchange"
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ template_home }}"
    mode: 0600
  with_items:
    - "other_dummy_file"
